// Sprites 16×16 de los stickers que se encuentran en cofres del mapa — mismo
// sistema de roles de color que ItemSprites.tsx (k tinta, m medio, d sombra,
// f papel, a acento, b acento suave, w fondo), así se repintan solos en los
// tres temas. Cada sticker tiene su dibujo en reposo y, según el caso, un
// cuadro de "reacción" (lo que se ve mientras el alumno lo toca) o etapas que
// cambian para siempre a fuerza de toques (el huevo que se raja y nace).

export const CHEST_SPRITES: Record<string, string[]> = {
  // ── Acto I · Serpiente Py (cofre del bosque) ──
  'cs-py': [
    '................',
    '....kkkkk.......',
    '...kbbbbbk......',
    '..kbbbbwkbk.....',
    '..kbbbbbbbbk....',
    '..kbbbkkkkkk....',
    '...kbbk.........',
    '....kbbk........',
    '...kkbbbk.......',
    '..kbbmbbbkkkk...',
    '.kbbbkkkbbbbbk..',
    '.kbmk...kkmbbk..',
    '.kbbbkkkkbabbk..',
    '..kbbbbmbbbbk...',
    '...kkkkkkkkk....',
    '................',
  ],
  'cs-py-poke': [
    '................',
    '....kkkkk.......',
    '...kbbbbbk......',
    '..kbbbbwkbk.....',
    '..kbbbbbbbbk..a.',
    '..kbbbkkkkkkaa..',
    '...kbbk.......a.',
    '....kbbk........',
    '...kkbbbk.......',
    '..kbbmbbbkkkk...',
    '.kbbbkkkbbbbbk..',
    '.kbmk...kkmbbk..',
    '.kbbbkkkkbabbk..',
    '..kbbbbmbbbbk...',
    '...kkkkkkkkk....',
    '................',
  ],

  // ── Acto I · Slime while True (cofre secreto) ──
  'cs-slime': [
    '................',
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kbffbbbbbbbk..',
    '..kbfbbbbbbbbk..',
    '..kbbkkbbbkkbk..',
    '..kbbkkbbbkkbk..',
    '..kbbbbbkbbbbk..',
    '..kbbbbbbbbbbk..',
    '..kbbbbaabbbbk..',
    '..kbbbaaaabbbk..',
    '..kbbbbaabbbbk..',
    '..kdbbbbbbbbdk..',
    '...kkkkkkkkkk...',
    '................',
  ],
  'cs-slime-poke': [
    '................',
    '................',
    '................',
    '................',
    '................',
    '................',
    '..kkkkkkkkkkkk..',
    '.kbffbbbbbbbbbk.',
    '.kbbkkbbbbkkbbk.',
    '.kbbbbbkkbbbbbk.',
    '.kbbbbbaabbbbbk.',
    'kbbbbbaaaabbbbbk',
    'kbbbbbbaabbbbbbk',
    'kdbbbbbbbbbbbbdk',
    '.kkkkkkkkkkkkkk.',
    '................',
  ],
  // Después del break: ojitos cerrados y sonrisa — por fin se quedó quieto.
  'cs-slime-calm': [
    '................',
    '................',
    '................',
    '...kkkkkkkkkk...',
    '..kbffbbbbbbbk..',
    '..kbfbbbbbbbbk..',
    '..kbbbbbbbbbbk..',
    '..kbkkbbbbkkbk..',
    '..kbbkbbbbkbbk..',
    '..kbbbkkkkbbbk..',
    '..kbbbbaabbbbk..',
    '..kbbbaaaabbbk..',
    '..kbbbbaabbbbk..',
    '..kdbbbbbbbbdk..',
    '...kkkkkkkkkk...',
    '................',
  ],

  // ── Acto II · Botella al mar (cofre flotando) ──
  'cs-botella': [
    '......kkkk......',
    '......kmmk......',
    '......kmmk......',
    '.....kkkkkk.....',
    '......kffk......',
    '.....kfbbfk.....',
    '....kfbbbbbk....',
    '...kfbwwwwbbk...',
    '...kfbwmmwbbk...',
    '...kfbwwwwbbk...',
    '...kfbwmmwbbk...',
    '...kfbwwwwbbk...',
    '...kfbbbbbbbk...',
    '...kaaaaaaaak...',
    '....kkkkkkkk....',
    '................',
  ],
  'cs-botella-poke': [
    '...........kk...',
    '..........kmmk..',
    '.......kk..kk...',
    '......kwwk......',
    '......kwmk......',
    '.....kfwwfk.....',
    '....kfbwmbbk....',
    '...kfbbwwbbbk...',
    '...kfbbbbbbbk...',
    '...kfbbbbbbbk...',
    '...kfbbbbbbbk...',
    '...kfbbbbbbbk...',
    '...kfbbbbbbbk...',
    '...kaaaaaaaak...',
    '....kkkkkkkk....',
    '................',
  ],

  // ── Acto II · Kraken NULL (cofre secreto, bajo el agua) ──
  'cs-null': [
    '................',
    '.....kkkkkk.....',
    '....kmmmmmmk....',
    '...kmffmmmmmk...',
    '...kmfmmmmmmk...',
    '...kmwwmmwwmk...',
    '...kmwammwamk...',
    '...kmmmmmmmmk...',
    '...kmmmddmmmk...',
    '..kmmmmmmmmmmk..',
    '..kmkmkmmkmkmk..',
    '..kmkmkmmkmkmk..',
    '.kmk.km..mk.kmk.',
    '.kak..ka.ak..kak',
    '..k....k..k...k.',
    '................',
  ],
  // Se desvanece: queda el contorno salteado y los ojos. ¿Está o no está?
  'cs-null-poke': [
    '................',
    '.....d.d.d......',
    '....d...........',
    '...d............',
    '............d...',
    '...d............',
    '......a...a.d...',
    '...d............',
    '............d...',
    '.............d..',
    '..d.d.d.........',
    '.........d.d.d..',
    '..........d.d.d.',
    '.dad...a.a...dad',
    '..d.......d...d.',
    '................',
  ],

  // ── Acto III · Huevo de Dragón (cofre en la orilla) — 3 etapas ──
  'cs-huevo': [
    '................',
    '................',
    '......kkkk......',
    '.....kffffk.....',
    '....kffaaffk....',
    '....kfaaffmk....',
    '...kfffffffmk...',
    '...kffffaafmk...',
    '...kfaafffamk...',
    '...kfaaffffmk...',
    '...kffffaafmk...',
    '...kmffffffmk...',
    '....kmffffmk....',
    '.....kmmmmk.....',
    '......kkkk......',
    '................',
  ],
  'cs-huevo-crack': [
    '................',
    '................',
    '......kkkk......',
    '.....kffffk.....',
    '....kffaaffk....',
    '....kfaaffmk....',
    '...kffkfffkmk...',
    '...kkkfkakfkk...',
    '...kfaafkfamk...',
    '...kfaaffffmk...',
    '...kffffaafmk...',
    '...kmffffffmk...',
    '....kmffffmk....',
    '.....kmmmmk.....',
    '......kkkk......',
    '................',
  ],
  'cs-huevo-dragon': [
    '................',
    '....k......k....',
    '...kbk....kbk...',
    '...kbbkkkkbbk...',
    '..kaaaaaaaaaak..',
    '..kawkaaaawkak..',
    '..kaaaaaaaaaak..',
    '..kaaakaakaaak..',
    '...kaakkkkaak...',
    '...kfkffffkfk...',
    '...kfffffffmk...',
    '...kmffffffmk...',
    '....kmffffmk....',
    '.....kmmmmk.....',
    '......kkkk......',
    '................',
  ],
  'cs-huevo-dragon-poke': [
    '..........a.....',
    '....k....a.k.a..',
    '...kbk....kbk...',
    '...kbbkkkkbbk...',
    '..kaaaaaaaaaak..',
    '..kakkaaaakkak..',
    '..kaaaaaaaaaak..',
    '..kaaakaakaaak..',
    '...kaakffkaak...',
    '...kfkkkkkkfk...',
    '...kfffffffmk...',
    '...kmffffffmk...',
    '....kmffffmk....',
    '.....kmmmmk.....',
    '......kkkk......',
    '................',
  ],

  // ── Acto III · Eslabón del Nexo (cofre secreto entre los árboles) ──
  'cs-nexo': [
    '................',
    '................',
    '................',
    '................',
    '.kkkkk....kkkkk.',
    'kbbbbbk..kmmmmmk',
    'kbk.kbk..kmk.kmk',
    'kbk.kbk..kmk.kmk',
    'kbk.kbk..kmk.kmk',
    'kbk.kbk..kmk.kmk',
    'kbbbbbk..kmmmmmk',
    '.kkkkk....kkkkk.',
    '................',
    '................',
    '................',
    '................',
  ],
  'cs-nexo-poke': [
    '................',
    '................',
    '......a..a......',
    '.......aa.......',
    '.kkkkk....kkkkk.',
    'kbbbbbk..kmmmmmk',
    'kbkakbkaakmkakmk',
    'kbkakbkaakmkakmk',
    'kbkakbkaakmkakmk',
    'kbkakbkaakmkakmk',
    'kbbbbbk..kmmmmmk',
    '.kkkkk....kkkkk.',
    '.......aa.......',
    '......a..a......',
    '................',
    '................',
  ],

  // ── Acto IV · Ojo del Arquitecto (cofre corrupto) ──
  'cs-ojo': [
    '................',
    '................',
    '..d.d.d..d.d.d..',
    '................',
    '.....kkkkkk.....',
    '...kkffffffkk...',
    '..kffffaaffffk..',
    '.kfffaawkaafffk.',
    'kffffakkkkaffffk',
    '.kfffaakkaafffk.',
    '..kffffaaffffk..',
    '...kkffffffkk...',
    '.....kkkkkk.....',
    '................',
    '..d.d.d..d.d.d..',
    '................',
  ],
  'cs-ojo-poke': [
    '................',
    '..........aaa...',
    '..d.d.d..d.d.d..',
    '................',
    '.....kkkkkk.....',
    '...kkffffffkk...',
    '....kffffaaffffk',
    '.kfffaawkaafffk.',
    'ffffakkkkaffffk.',
    '.kfffaakkaafffk.',
    '..kffffaaffffk..',
    '...kkffffffkk...',
    '.....kkkkkk..aaa',
    '................',
    '..d.d.d..d.d.d..',
    '................',
  ],

  // ── Acto IV · El Gato (cofre secreto, sellado hasta vencer al Arquitecto) ──
  'cs-gato': [
    '................',
    '..kk........kk..',
    '..kak......kak..',
    '..kaak....kaak..',
    '..kffkkkkkkffk..',
    '.kffffffffffffk.',
    '.kffkkffffkkffk.',
    '.kffkwffffkwffk.',
    '.kffffffffffffk.',
    'kkfffffaafffffkk',
    '.kbfffkffkfffbk.',
    '.kfffffkkfffffk.',
    '..kmffffffffmk..',
    '...kkkkkkkkkk...',
    '................',
    '................',
  ],
  'cs-gato-poke': [
    '................',
    '..kk........kk..',
    '..kak......kak..',
    '..kaak....kaak..',
    '..kffkkkkkkffk..',
    '.kffffffffffffk.',
    '.kfffkffffkfffk.',
    '.kffkfkffkfkffk.',
    '.kffffffffffffk.',
    'kkfffffaafffffkk',
    '.kbfffkffkfffbk.',
    '.kffffkaakffffk.',
    '..kmfffkkfffmk..',
    '...kkkkkkkkkk...',
    '................',
    '................',
  ],
}

/** Animación leve en reposo (mismas clases item-anim-* del inventario). */
export const CHEST_SPRITE_ANIM: Record<string, string> = {
  'cs-py': 'item-anim-sway',
  'cs-slime': 'item-anim-squash',
  'cs-botella': 'item-anim-bob',
  'cs-null': 'item-anim-drift',
  'cs-huevo': 'item-anim-jiggle',
  'cs-huevo-crack': 'item-anim-jiggle',
  'cs-huevo-dragon': 'item-anim-waddle',
  'cs-nexo': 'item-anim-pulse',
  'cs-ojo': 'item-anim-flicker',
  'cs-gato': 'item-anim-bob',
}
