import type { Boss } from '@/types'

export const BOSSES: Boss[] = [
  {
    id: 'creeper-formulario',
    classNumber: 1,
    name: 'Creeper Formulario',
    title: 'BOSS-01',
    topic: 'Variables y tipos de datos',
    type: 'python',
    hpMax: 150,
    color: '#22C55E',
    description: 'Asigna las variables correctas antes de que la bomba explote.',
  },
  {
    id: 'guardian-puerta',
    classNumber: 2,
    name: 'Guardián de la Puerta',
    title: 'BOSS-02',
    topic: 'Condicionales if / elif / else',
    type: 'python',
    hpMax: 180,
    color: '#4ADE80',
    description: 'Solo la condición correcta abre el portal al siguiente nivel.',
  },
  {
    id: 'golem-infinito',
    classNumber: 3,
    name: 'Golem Infinito',
    title: 'BOSS-03',
    topic: 'Bucles for y while',
    type: 'python',
    hpMax: 200,
    color: '#86EFAC',
    description: 'Ejecuta exactamente las iteraciones necesarias. Ni una más.',
  },
  {
    id: 'mercader-abismo',
    classNumber: 4,
    name: 'Mercader del Abismo',
    title: 'BOSS-04',
    topic: 'Listas de diccionarios',
    type: 'python',
    hpMax: 220,
    color: '#16A34A',
    description: 'Construye el inventario exacto que el mercader exige.',
  },
  {
    id: 'maestro-craftero',
    classNumber: 5,
    name: 'Maestro Craftero',
    title: 'BOSS-05',
    topic: 'Funciones con parámetros',
    type: 'python',
    hpMax: 240,
    color: '#15803D',
    description: 'Define la función correcta. def es tu espada.',
  },
  {
    id: 'archivista',
    classNumber: 6,
    name: 'El Archivista',
    title: 'BOSS-06',
    topic: 'De listas a tablas',
    type: 'python',
    hpMax: 260,
    color: '#166534',
    description: 'Traduce la lista de Python al esquema de tabla correcto.',
  },
  {
    id: 'constructor-vacio',
    classNumber: 7,
    name: 'Constructor del Vacío',
    title: 'BOSS-07',
    topic: 'CREATE TABLE · INSERT INTO',
    type: 'sql',
    hpMax: 280,
    color: '#38BDF8',
    description: 'Crea la tabla con los tipos correctos. Puebla el vacío.',
  },
  {
    id: 'oraculo-oscuro',
    classNumber: 8,
    name: 'Oráculo Oscuro',
    title: 'BOSS-08',
    topic: 'SELECT · WHERE · ORDER BY',
    type: 'sql',
    hpMax: 300,
    color: '#7DD3FC',
    description: 'La consulta exacta revela la verdad. El WHERE es la clave.',
  },
  {
    id: 'contador-almas',
    classNumber: 9,
    name: 'Contador de Almas',
    title: 'BOSS-09',
    topic: 'COUNT · SUM · AVG · GROUP BY',
    type: 'sql',
    hpMax: 320,
    color: '#0EA5E9',
    description: 'Agrega los datos correctamente. Sin GROUP BY no hay victoria.',
  },
  {
    id: 'falsificador',
    classNumber: 10,
    name: 'El Falsificador',
    title: 'BOSS-10',
    topic: 'UPDATE · DELETE',
    type: 'sql',
    hpMax: 340,
    color: '#0284C7',
    description: 'Modifica solo lo necesario. Un DELETE sin WHERE te destruye.',
  },
  {
    id: 'el-nexo',
    classNumber: 11,
    name: 'El Nexo',
    title: 'BOSS-11',
    topic: 'Python + sqlite3',
    type: 'mixed',
    hpMax: 360,
    color: '#A78BFA',
    description: 'Conecta los dos mundos. cursor.execute es el puente.',
  },
  {
    id: 'la-hydra',
    classNumber: 12,
    name: 'La Hydra',
    title: 'BOSS-12',
    topic: 'Proyecto: agregar y listar',
    type: 'mixed',
    hpMax: 380,
    color: '#8B5CF6',
    description: 'Corta una cabeza y crecen dos. Persiste los datos o vuelven.',
  },
  {
    id: 'dragon-rojo',
    classNumber: 13,
    name: 'Dragón Rojo',
    title: 'BOSS-13',
    topic: 'Proyecto: buscar, quitar, actualizar',
    type: 'mixed',
    hpMax: 400,
    color: '#7C3AED',
    description: 'buscar_item + quitar con confirmación + UPDATE preciso.',
  },
  {
    id: 'el-arquitecto',
    classNumber: 14,
    name: 'El Arquitecto',
    title: 'BOSS-FINAL',
    topic: 'Sistema completo · todo integrado',
    type: 'final',
    hpMax: 500,
    color: '#F59E0B',
    description: 'El jefe que diseñó el mundo. Demuestra que entendés el sistema.',
  },
]

export function getBossById(id: string): Boss | undefined {
  return BOSSES.find((b) => b.id === id)
}

export function getBossByClass(classNumber: number): Boss | undefined {
  return BOSSES.find((b) => b.classNumber === classNumber)
}

export const BOSS_TYPE_COLORS: Record<string, string> = {
  python: '#22C55E',
  sql:    '#38BDF8',
  mixed:  '#A78BFA',
  final:  '#F59E0B',
}
